### ISSUE TITLE
Can not reproduce 2018-03 due to figure overlaps

### ISSUE THREAD

**Issue by hope-data-science** [Z3tt/TidyTuesday#4]
Hello there, thank you for the awesome work to reach so many wonderful figures via ggplot2. I have an issue when reproducing the 2018-03 figure, producing the following figure:
![image](https://user-images.githubusercontent.com/32947502/141709568-f0e3815b-c8d9-4d1b-bab6-b0c0f173589b.png)
I assume there are two problem occuring here: 1. the 3rd and 6th plot is covering the 2nd and 5th one; 2. fonts could not be loaded automatilcally. Furthermore, because the update of the packages, I find warnings listed as:
```
old-style crs object detected; please recreate object with a recent sf::st_crs()
Warning messages:
1: It is deprecated to specify `guide = FALSE` to remove a guide. Please use `guide = "none"` instead. 
```
Is there any way to figure them out? Thanks.

**Comment by z3tt** [comment]
Hi, thanks for your feedback and reporting the issue. 

1. To address the warning, replace `guide = FALSE` by `guide = "none"`. This is due to an update of the `scale_*` functions of ggplot2.
2. To make the fonts work, you need to install them locally on your system. Nowadays, the `{systemfonts}` does the best job when it comes to using custom fonts. Maybe try that instead.
3. To fix the overlap, one has to use transparent backgrounds for the single maps. Try adjusting the `plot.background` of the theme accordingly: `theme(plot.background = element_rect(fill = "transparent", color = "transparent")`.

I currently have no time to try it myself but I hope this solves your issues!

**Comment by hope-data-science** [comment]
Thank you for the response.
1. The first warning could be fixed when we use `guide = "none"` instead.
2. Currently we want to seek a way to restore the fonts once we used, is there any way to do that? Maybe saving the fonts in a folder and load it once we need. Currently I am using `{showtext}` package and use Google fonts or local fonts, but I have to specify them every time I use them. And sometimes they are not working. Any hints for more convience?
3. The codes `theme(plot.background = element_rect(fill = "transparent", color = "transparent"))` is working when I add them to the 3rd and 6th figures and arrange them again. 

Thanks.
